server:
  # 端口号任意
  port: 9264

spring:
  # 更改 spring security 的 name 和 password
  # 否则需要使用 security 自动生成的随机密码
  # 没有此配置，则随机密码会随启动开始打印在 terminal 里
  security:
    user:
      # 更改登陆用户名，无此配置默认为 user，此处与默认用户名相同
      name: user
      # 更改默认密码
      password: password
#      roles: admin